name: Runmain

on:
  push:
    branches:
      - dataset  # Trigger on dataset branch push

  workflow_dispatch:

jobs:
  run-main-py:
    runs-on: [self-hosted, linux, ARM64]
    steps:
      - name: Checkout dataset branch
        uses: actions/checkout@v2
        with:
          ref: dataset

      - name: Enable Debugging
        run: |
          echo "GITHUB_ACTIONS_DEBUG=true" >> $GITHUB_ENV

      - name: Set up AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
      - name: Set up pyenv and activate virtual environment
        run: |
          export PATH="$HOME/.pyenv/bin:$PATH"
          eval "$(pyenv init --path)"
          eval "$(pyenv init -)"
          eval "$(pyenv virtualenv-init -)"
          pyenv activate plytube
          pyenv --version

      - name: Run mlflow server
        run: |
          cd /home/ubuntu/ply-tube
          nohup mlflow server --host 0.0.0.0 --port 5000 > mlflow_server.log 2>&1 &

      - name : Pull and execute main file
        run: |          
          cd /home/ubuntu/feature_store
          dvc pull
          python /home/ubuntu/ply-tube/main.py
