# name: Runmain

on:
  push:
    branches:
      - dataset

jobs:
  run-main-py:
    runs-on: [self-hosted, linux, ARM64]

    steps:
      - name: Checkout dataset branch
        uses: actions/checkout@v2
        with:
          ref: dataset

      - name: 디버그 로그 보기
        run: |
          echo "GITHUB_ACTIONS_DEBUG=true" >> $GITHUB_ENV
      
      - name: 가상환경 활성화하고 확인하기
        run: |
          export PATH="$HOME/.pyenv/bin:$PATH"
          eval "$(pyenv init --path)"
          eval "$(pyenv init -)"
          eval "$(pyenv virtualenv-init -)"
          pyenv activate plytube
          pyenv shell plytube
          pyenv --version
          pip freeze | grep dvc
      
      - name: 모델 학습
        run: |
          echo "AWS credential 설정완료"
          export PATH="$HOME/.pyenv/bin:$PATH"
          eval "$(pyenv init --path)"
          eval "$(pyenv init -)"
          eval "$(pyenv virtualenv-init -)"
          pyenv activate plytube
          cd /home/ubuntu/feature_store
          dvc version
          dvc pull
          cd /home/ubuntu/ply-tube
          nohup mlflow server --host 0.0.0.0 --port 5000 > mlflow_server.log 2>&1 &
          python /home/ubuntu/ply-tube/main.py
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: 추론서버 띄우기
        run: |
          echo "AWS credential 설정완료"
          export PATH="$HOME/.pyenv/bin:$PATH"
          eval "$(pyenv init --path)"
          eval "$(pyenv init -)"
          eval "$(pyenv virtualenv-init -)"
          pyenv activate ply-tube
          pkill -f mlflow
          cd /home/ubuntu/ply-tube
          nohup mlflow server --host 0.0.0.0 --port 5000 > mlflow_server.log 2>&1 &
          python /home/ubuntu/ply-tube/app.py
          curl http://localhost:5001/health
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
      
