name: Runmain

on:
  push:
    branches:
      - dataset 

jobs:
  run-main-py:
    runs-on: server02  

    steps:
    - name: Checkout dataset branch
      uses: actions/checkout@v2
      with:
        ref: dataset  
        
    - name: Set up pyenv and activate virtual environment
      run: |
        export PATH="$HOME/.pyenv/bin:$PATH"
        eval "$(pyenv init --path)"
        eval "$(pyenv init -)"
        eval "$(pyenv virtualenv-init -)"
        pyenv activate plytube  
        dvc pull
        python /home/ubuntu/ply-tube/main.py
