name: Run main.py

on:
  push:
    branches:
      - dataset  # Trigger on push to the dataset branch

jobs:
  run-main-py:
    runs-on: server02  # Self-hosted Runner

    steps:
    # 1. Checkout the dataset branch
    - name: Checkout dataset branch
      uses: actions/checkout@v2
      with:
        ref: dataset  # Change this to dataset if needed

    # 2. Set up pyenv and activate plytube virtual environment
    - name: Set up pyenv and activate virtual environment
      run: |
        export PATH="$HOME/.pyenv/bin:$PATH"
        eval "$(pyenv init --path)"
        eval "$(pyenv init -)"
        eval "$(pyenv virtualenv-init -)"
        pyenv activate plytube  # Activate plytube environment
        dvc pull  # Pull data from DVC
